version: "2"

services:
  spring-boot-reactive:
    build:
      context: ../spring-initializr
    image: spring-initializr-tpd
    ports:
      - "8080:8080"
    networks:
      - network-reactive

networks:
  network-reactive:
